import { Geist, Geist_Mono } from "next/font/google";
import "./_styles/globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/navbar";
import Footer from "./_components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Toaster
          position="top-center"
          gutter={12}
          containerStyle={{ margin: "8px" }}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
            style: {
              fontSize: "16px",
              maxWidth: "500px",
              padding: "16px 24px",
              backgroundColor: "#ffffff",
              color: "var(--color-grey-700)",
            },
          }}
        />
        <main className="bg-gradient-to-br from-[#f0fdf4] via-[#ecfdf5] to-[#dcfce7] ">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
